stages:
  - build
  - push

build:
  image: node:lts-alpine
  stage: build
  script:
    - echo $VUE_APP_AUTH_URL
    - echo "VUE_APP_AUTH_URL=$VUE_APP_AUTH_URL" >> .env.production
    - echo "VUE_APP_BACKEND_URL=$VUE_APP_BACKEND_URL" >> .env.production
    - echo "VUE_APP_AUTH_AUDIENCE=$VUE_APP_AUTH_AUDIENCE" >> .env.production
    - echo "VUE_APP_AUTH_COOKIE_DOMAIN=$VUE_APP_AUTH_COOKIE_DOMAIN" >> .env.production
    - echo "VUE_APP_CLIENT_ID=$VUE_APP_CLIENT_ID" >> .env.production
    - echo "VUE_APP_CLIENT_SECRET=$VUE_APP_CLIENT_SECRET" >> .env.production
    - chmod +x .env.production
    - npm install && npm run build
  artifacts:
    paths:
      - dist
push:
  stage: push
  only:
    - master
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY/pdelert/plant-front .
    - docker push $CI_REGISTRY/pdelert/plant-front
