stages:
  - envs
  - build
  - push

envs:
  stage: envs
  script:
    - echo $VUE_APP_AUTH_URL >> .env
    - echo $VUE_APP_BACKEND_URL >> .env
    - echo $VUE_APP_AUTH_AUDIENCE >> .env
    - echo $VUE_APP_AUTH_COOKIE_DOMAIN >> .env
    - echo $VUE_APP_CLIENT_ID >> .env
    - echo $VUE_APP_CLIENT_SECRET >> .env
  artifacts:
    paths:
      - .env
#    reports:
#      dotenv: .env
build:
  image: node:lts-alpine
  stage: build
  script: ls -la && npm install && npm run build
  artifacts:
    paths:
      - dist
push:
  stage: push
  only:
    - master
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY/pdelert/plant-front .
    - docker push $CI_REGISTRY/pdelert/plant-front
